//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblFEmployee
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        [StringLength(25, ErrorMessage = "Name cannot Exceed 25 characters")]
        public string Name { get; set; }
        public string Designation { get; set; }
        [Required(ErrorMessage = "Age is Required")]
        [Range(10, 99, ErrorMessage = "Age cannot be more than 2 digits")]
        public int Age { get; set; }
        [Required(ErrorMessage = "DOB is Required")]
        public System.DateTime DOB { get; set; }
        [Required(ErrorMessage = "Gender is Required")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "This field is Required")]
        public string Street_Address1 { get; set; }
        public string Street_Address2 { get; set; }
        
        
    }
}
